### ISSUE TITLE
Check for redudant reptition of numbers and numerals

### ISSUE THREAD

**Issue by anseljh** [commonform/commonform-critique#1]
See https://github.com/kemitchell/american-legal-archaisms/issues/3, where I say:

> How do you want to handle redundant numbers, e.g., "two (2)"?
> We could write out at least one through ten (1-10) or so, but what would be an appropriate more general approach to this class of repeated redundancy and re-recital?

and @kemitchell says:

> Thanks for this.
> I think we see eye to eye on that practice, but I wouldn't call it archaic, just error-prone.
> I'd definitely like to add those checks---probably based on a regex---to an annotator. But this package [american-legal-archaisms] hopefully stays a very small list of words and phrases.

**Comment by anseljh** [comment]
Starting a new regex annotator package here: https://github.com/anseljh/doubleplus-numbers

**Comment by kemitchell** [comment]
You may find [commonform-regexp-annotator](https://www.npmjs.com/package/commonform-regexp-annotator) handy.

**Comment by anseljh** [comment]
Indeed! A big help. I made a valiant attempt, but it's not quite working yet. 

Build error output here: https://gist.github.com/anseljh/c5ceaca532643ac81f5a

Any ideas?

**Comment by kemitchell** [comment]
Would you mind pushing your code?

**Comment by anseljh** [comment]
Moving this thread to https://github.com/anseljh/doubleplus-numbers/issues/1
